<?php

namespace App\Filament\Resources\EmailSettings\Schemas;

use App\Support\EmailNotificationCatalog;
use Filament\Forms\Components\CheckboxList;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class EmailSettingForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Sending')
                    ->description('Amazon SES is the outgoing mail provider for this site. Use a sender address verified in SES.')
                    ->schema([
                        Hidden::make('provider')
                            ->default('ses_smtp')
                            ->dehydrateStateUsing(fn (): string => 'ses_smtp'),
                        Toggle::make('mail_enabled')
                            ->label('Enable Amazon SES email')
                            ->default(true),
                        TextInput::make('from_name')
                            ->label('From name')
                            ->maxLength(255),
                        TextInput::make('from_email')
                            ->label('Verified sender email')
                            ->email()
                            ->helperText('This must be a verified SES email identity, or an address on a verified SES domain.')
                            ->maxLength(255),
                        TextInput::make('reply_to_email')
                            ->label('Reply-to email')
                            ->email()
                            ->maxLength(255),
                    ])
                    ->columns(2),
                Section::make('Amazon SES SMTP')
                    ->description('Use the SMTP credentials generated by Amazon SES for your selected region. Keep the password blank when you do not want to replace the saved value.')
                    ->schema([
                        TextInput::make('ses_region')
                            ->label('SES region')
                            ->placeholder('eu-west-1')
                            ->default('eu-west-1')
                            ->formatStateUsing(fn (?string $state): string => $state ?: 'eu-west-1')
                            ->helperText('The current project is set up in Europe (Ireland), usually eu-west-1.')
                            ->maxLength(255),
                        TextInput::make('smtp_username')
                            ->label('SMTP username')
                            ->helperText('Use the SMTP username created in Amazon SES, not your AWS access key.')
                            ->maxLength(255),
                        TextInput::make('smtp_password')
                            ->label('SMTP password')
                            ->password()
                            ->revealable()
                            ->helperText('Leave blank to keep the saved password.')
                            ->formatStateUsing(fn (): ?string => null)
                            ->dehydrated(fn (?string $state): bool => filled($state)),
                        TextInput::make('smtp_port')
                            ->label('SMTP port')
                            ->numeric()
                            ->default(587)
                            ->formatStateUsing(fn ($state): int => $state ?: 587)
                            ->minValue(1)
                            ->maxValue(65535),
                        Select::make('smtp_encryption')
                            ->label('Connection security')
                            ->options([
                                'tls' => 'STARTTLS / TLS (port 587)',
                                'ssl' => 'SSL / SMTPS (port 465)',
                            ])
                            ->default('tls')
                            ->formatStateUsing(fn (?string $state): string => $state ?: 'tls'),
                    ])
                    ->columns(3),
                Section::make('Enabled notification emails')
                    ->description('Templates also have their own on/off switch. Both switches must be on before a notification is sent.')
                    ->schema([
                        CheckboxList::make('notification_toggles')
                            ->label('Notifications')
                            ->options(EmailNotificationCatalog::toggleOptions())
                            ->default(EmailNotificationCatalog::defaultEnabledKeys())
                            ->bulkToggleable()
                            ->columns(2)
                            ->columnSpanFull(),
                    ]),
            ]);
    }
}
